---
title: "Gov 50 Final Project"
author: Althea Lee
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

I am interested in exploring data about Singapore's socioeconomic classes and how it relates to willingness to vote for the opposition. 

Classified within political theory, Singapore can be identified as benevolent totalitarian, competitive authoritarian, or a de-facto one party state. Though the Singaporean government recognizing itself as a democratic country, reality of the political landscape argues differently. Election frameworks are skewed towards the ruling party's (PAP) victory, rampant censorship stymies civic education, restrictions and legislatures against public assembly erode collective action efforts, and government schemes entrench citizens in voting for the PAP. Moreover, measures such as v-dem and freedom house identify Singapore as undemocratic (0.4 on v-dem electoral democracy index and 47/100 on global freedom score). 

Much of Singapore's geographic and spatial distribution relies on socioeconomic class, primarily income from work. The country is divided into 5 different income classes: Upper class, Upper middle class, Intermediate middle class, Lower middle class, and Working class. 

I suspect that lower-class individuals are more willing to vote for the opposition for reasons twofold (demographic and psychographic). Firstly, lower-class voters have already experienced the short-end of the electoral stick in the form of institutional barriers: indebtedness from government housing schemes, a widening skills gap, and elitist career recruitment programs - all culminating towards low social mobility. Thus, animosity towards the ruling party may be a natural voting attitude. Secondly, lower-class voters tend to settle within constituencies where the opposition's victory has been long-standing. Residing in these constituencies are accompanied with the expectation that the opposition party will control quality of life within the area - a psychographic decision in value and political judgements. 

I believe that data analysis should exist in order to evaluate how much of Singapore's geographical distribution correlates to (and perhaps affects) an individual's political alignment. This can help us understand how landscape can be manipulated to tighten political reigns (i.e. ostracize political threats) and predict future voting outcomes in the next elections (2025). 

## Milestone 2

Does social class and area of residence influence voting patterns in Singapore’s general elections? For my final project, I intend to study whether social classes and constituencies share any trends with the results of the 2020 General Elections in Singapore. I hypothesize that in constituencies with lower-class residents, votes for the opposition will be greater. 

In constituencies with a greater proportion of lower-income individuals, fewer will be obliged to vote for the ruling party because they have experienced discriminatory policies such as in education and housing. 

In constituencies with a greater proportion of higher-income individuals, more will be obliged to vote for the ruling party because they house a greater percentage of elites who have a stake in the election results through private benefits such as institutionalized ties, tax refunds, policy decision making power, and more. 

My sample includes all electoral constituencies (31 in total) in the 2020 General Elections. 

My unit of analysis is Singapore’s General Election in 2020. 

The explanatory variable of interest is whether the ruling party or the opposition won in the constituency. This variable is coded =1 for the opposition’s victory and coded =0 for the ruling party’s victory. 

My outcome variable is the number of votes for the opposition. For instance, if the variable were coded =100, there were 100 votes for the opposition. 

If I observe a greater number of opposition votes in “lower-class” constituencies, then this would support my hypothesis.  However, if I observe a greater number of ruling party votes in “lower-class” constituencies, then this would provide evidence to reject my hypothesis. 

When I run my regression of the count of opposition party votes on the lower-class constituency variable, a positive, significant coefficient would support my hypothesis. 

The databases that will be used for this project include: 
- https://tablebuilder.singstat.gov.sg/table/CT/17571 
- https://data.gov.sg/dataset/parliamentary-general-election-results
- https://data.gov.sg/dataset/parliamentary-general-election-results?resource_id=f33c3652-ec6a-46e6-9c04-4f5c869d99b2


fsdakjfdhaskjdf
